// harness v2 (SC-5859) — generated by `harness init`; change the template in ~/Development/harness, never this file
import { defineConfig } from 'vitest/config';
export default defineConfig({
  test: {
    include: ['src/**/*.test.ts', 'test/**/*.test.ts'],
    coverage: { provider: 'v8', reporter: ['text-summary', 'lcov', 'json-summary'], reportsDirectory: 'coverage' },
  },
});
