#!/usr/bin/env node
// Regenerate the README index and data/ports.json from ports/*.yml.
// Usage: node scripts/build.mjs [--check]   (--check fails if output is stale)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadPorts } from './lib.mjs';

const START = '<!-- INDEX:START (generated by scripts/build.mjs, do not edit) -->';
const END = '<!-- INDEX:END -->';

const SECTIONS = [
  ['standalone', 'Standalone (runs on the headset)'],
  ['both', 'PCVR and standalone'],
  ['pcvr', 'PCVR'],
];
const STATUS = { alpha: '🧪 alpha', beta: '🚧 beta', stable: '✅ stable', abandoned: '💀 abandoned' };

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const authors = (p) => p.authors.map((a) => (a.url ? `[${cell(a.name)}](${a.url})` : cell(a.name))).join(', ');

function table(ports) {
  const rows = ports.map((p) =>
    [
      `[${cell(p.name)}](${p.source_url})`,
      cell(p.games.join(', ')),
      STATUS[p.status],
      `[${cell(p.version)}](${p.download_url}) · ${p.version_date}`,
      authors(p),
      p.known_bugs.length ? `${p.known_bugs.length} known` : '—',
    ].join(' | '),
  );
  return [
    '| Port | Game(s) | Status | Latest | Author | Bugs |',
    '|---|---|---|---|---|---|',
    ...rows.map((r) => `| ${r} |`),
  ].join('\n');
}

export function render(ports) {
  const byName = (a, b) => a.name.localeCompare(b.name);
  const parts = [`**${ports.length} ports indexed.** Machine-readable copy: [\`data/ports.json\`](data/ports.json).`];
  for (const [cat, title] of [
    ['mod', 'Dedicated VR mods and source ports'],
    ['injector', 'Universal injectors'],
  ]) {
    const inCat = ports.filter((p) => (cat === 'mod' ? p.category !== 'injector' : p.category === 'injector'));
    if (!inCat.length) continue;
    parts.push(`## ${title}`);
    for (const [plat, heading] of SECTIONS) {
      const group = inCat.filter((p) => p.platform === plat).sort(byName);
      if (group.length) parts.push(`### ${heading}\n\n${table(group)}`);
    }
  }
  return parts.join('\n\n');
}

const { ports, errors } = loadPorts();
if (errors.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  process.exit(1);
}

const readmePath = join(ROOT, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s < 0 || e < s) {
  console.error('README.md is missing the INDEX markers');
  process.exit(1);
}
const nextReadme = `${readme.slice(0, s + START.length)}\n\n${render(ports)}\n\n${readme.slice(e)}`;
const json = `${JSON.stringify(
  ports.map(({ slug, ...rest }) => ({ slug, ...rest })),
  null,
  2,
)}\n`;

const jsonPath = join(ROOT, 'data/ports.json');
let currentJson = '';
try {
  currentJson = readFileSync(jsonPath, 'utf8');
} catch {
  // first build: no data/ports.json yet
}

if (process.argv.includes('--check')) {
  const stale = [nextReadme !== readme && 'README.md', json !== currentJson && 'data/ports.json'].filter(Boolean);
  if (stale.length) {
    console.error(`✗ ${stale.join(' and ')} out of date: run \`npm run build\` and commit the result.`);
    process.exit(1);
  }
  console.log('✓ README.md and data/ports.json up to date');
} else {
  writeFileSync(readmePath, nextReadme);
  mkdirSync(join(ROOT, 'data'), { recursive: true });
  writeFileSync(jsonPath, json);
  console.log(`✓ wrote README.md and data/ports.json (${ports.length} ports)`);
}
