#!/usr/bin/env node
// Regenerate the README index and data/ports.json from ports/*.yml.
// Usage: node scripts/build.mjs [--check]   (--check fails if output is stale)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadPorts } from './lib.mjs';
import { render } from './render.mjs';

const START = '<!-- INDEX:START (generated by scripts/build.mjs, do not edit) -->';
const END = '<!-- INDEX:END -->';

const { ports, errors } = loadPorts();
if (errors.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  process.exit(1);
}

const readmePath = join(ROOT, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s < 0 || e < s) {
  console.error('README.md is missing the INDEX markers');
  process.exit(1);
}
const nextReadme = `${readme.slice(0, s + START.length)}\n\n${render(ports)}\n\n${readme.slice(e)}`;
const json = `${JSON.stringify(
  ports.map(({ slug, ...rest }) => ({ slug, ...rest })),
  null,
  2,
)}\n`;

const jsonPath = join(ROOT, 'data/ports.json');
let currentJson = '';
try {
  currentJson = readFileSync(jsonPath, 'utf8');
} catch {
  // first build: no data/ports.json yet
}

if (process.argv.includes('--check')) {
  const stale = [nextReadme !== readme && 'README.md', json !== currentJson && 'data/ports.json'].filter(Boolean);
  if (stale.length) {
    console.error(`✗ ${stale.join(' and ')} out of date: run \`npm run build\` and commit the result.`);
    process.exit(1);
  }
  console.log('✓ README.md and data/ports.json up to date');
} else {
  writeFileSync(readmePath, nextReadme);
  mkdirSync(join(ROOT, 'data'), { recursive: true });
  writeFileSync(jsonPath, json);
  console.log(`✓ wrote README.md and data/ports.json (${ports.length} ports)`);
}
